# Generated by Django 4.2.15 on 2026-01-09 23:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.CharField(max_length=150)),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
                ("technologies", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("project_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("date_completed", models.DateField()),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-date_completed"],
            },
        ),
    ]
