# Generated by Django 6.0.1 on 2026-01-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("web-dev", "Web Development"),
                    ("ui-ux", "UI/UX Design"),
                    ("cloud", "Cloud & DevOps"),
                    ("game-dev", "Game Development"),
                    ("other", "Other"),
                ],
                default="web-dev",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
