# Generated by Django 4.2.15 on 2026-01-31 01:35

from django.db import migrations


def populate_categories(apps, schema_editor):
    Category = apps.get_model('portfolio', 'Category')

    categories = [
        {'name': 'web-dev', 'slug': 'web-dev', 'display_name': 'Web Development'},
        {'name': 'ui-ux', 'slug': 'ui-ux', 'display_name': 'UI/UX Design'},
        {'name': 'cloud', 'slug': 'cloud', 'display_name': 'Cloud & DevOps'},
        {'name': 'game-dev', 'slug': 'game-dev', 'display_name': 'Game Development'},
        {'name': 'other', 'slug': 'other', 'display_name': 'Other'},
    ]

    for category_data in categories:
        Category.objects.get_or_create(**category_data)


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_category_remove_project_category_project_categories"),
    ]

    operations = [
        migrations.RunPython(populate_categories),
    ]
